export const leaderboardData = [
  { nama: "John Doe", totalPoint: 100 },
  { nama: "Jane Smith", totalPoint: 80 },
  { nama: "Alice Johnson", totalPoint: 120 },
  { nama: "Bob Brown", totalPoint: 90 },
  { nama: "Michael Lee", totalPoint: 110 },
  { nama: "Emily Davis", totalPoint: 95 },
  { nama: "David Wilson", totalPoint: 85 },
  { nama: "Sarah Martinez", totalPoint: 105 },
  { nama: "James Taylor", totalPoint: 75 },
  { nama: "Olivia Anderson", totalPoint: 115 },
  { nama: "Daniel Thompson", totalPoint: 125 },
  { nama: "Sophia Garcia", totalPoint: 88 },
  { nama: "Matthew Rodriguez", totalPoint: 82 },
  { nama: "Chloe Lopez", totalPoint: 97 },
  { nama: "Benjamin Hernandez", totalPoint: 102 },
  { nama: "Emma King", totalPoint: 93 },
  { nama: "Ethan Scott", totalPoint: 80 },
  { nama: "Ava Young", totalPoint: 112 },
  { nama: "Noah Phillips", totalPoint: 99 },
  { nama: "Mia Nguyen", totalPoint: 87 },
];
