export const leaderboardData = [
  { nama: "John Doe", totalPoint: 100, shift: "Shift 1" },
  { nama: "Jane Smith", totalPoint: 80, shift: "Shift 2" },
  { nama: "Alice Johnson", totalPoint: 120, shift: "Shift 3" },
  { nama: "Bob Brown", totalPoint: 90, shift: "Shift 1" },
  { nama: "Michael Lee", totalPoint: 110, shift: "Shift 2" },
  { nama: "Emily Davis", totalPoint: 95, shift: "Shift 3" },
  { nama: "David Wilson", totalPoint: 85, shift: "Shift 1" },
  { nama: "Sarah Martinez", totalPoint: 105, shift: "Shift 2" },
  { nama: "James Taylor", totalPoint: 75, shift: "Shift 3" },
  { nama: "Olivia Anderson", totalPoint: 115, shift: "Shift 1" },
  { nama: "Daniel Thompson", totalPoint: 125, shift: "Shift 2" },
  { nama: "Sophia Garcia", totalPoint: 88, shift: "Shift 3" },
  { nama: "Matthew Rodriguez", totalPoint: 82, shift: "Shift 1" },
  { nama: "Chloe Lopez", totalPoint: 97, shift: "Shift 2" },
  { nama: "Benjamin Hernandez", totalPoint: 102, shift: "Shift 3" },
  { nama: "Emma King", totalPoint: 93, shift: "Shift 1" },
  { nama: "Ethan Scott", totalPoint: 80, shift: "Shift 2" },
  { nama: "Ava Young", totalPoint: 112, shift: "Shift 3" },
  { nama: "Noah Phillips", totalPoint: 99, shift: "Shift 1" },
  { nama: "Mia Nguyen", totalPoint: 87, shift: "Shift 2" },
];
